# GRADLE SETTINGS
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
javaVersion=21

# MOD SETTINGS
mod_id=hamzziticon
mod_name=HamzziTicon
mod_version=0.1.0
mod_group=kr.hamzzihouse
mod_description=햄찌하우스 티콘을 채팅에서 편하게 쓰기 위한 클라이언트 모드
mod_author=HamzziHouse
mod_license=All Rights Reserved
mod_homepage=https://modrinth.com/mod/hamzziticon
mod_issues=https://github.com/hamzzihouse/HamzziTicon/issues

# MINECRAFT
minecraft_version=1.21.11
neoform_version=1.21.11-20251209.172050

# FABRIC
fabric_loader_version=0.19.5
fabric_api_version=0.141.6+1.21.11

# NEOFORGE
neoforge_version=21.11.45


# TOOLING
loom_version=1.14-SNAPSHOT
moddevgradle_version=2.0.107
shadow_version=9.3.1
grgit_version=5.3.3

# LIBRARIES
jetbrains_annotations_version=26.0.2-1
lombok_version=1.18.42
junit_version=5.11.4
